- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- site/web/app/themes/sage/templates/header.php
- Actualizat logo
- Responsive menu
- Testat dimensiuni mari / mici
> Better header

- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/listing-campanii.php
- site/web/app/themes/sage/templates/listing-ghiduri.php
- site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
> feat(campaigns) Campaign listing page UI

- site/config/misc/fiipregatitro.wordpress.2018-02-05.xml
- site/web/app/lib/Entity/Campaign.php
- site/web/app/lib/Repository/CampaignRepository.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/content-single-campanie.php
- site/web/app/themes/sage/templates/content-single-ghid.php
- site/web/app/themes/sage/templates/mustache/campaign.mustache
It's all here, except the attachment `list`. We don't have a repeater
field in ACF so until we build one we have to stick with what we got.
> feat(campaign) Built campaign detail page

- site/web/app/themes/sage/templates/mustache/app_promo.mustache
Added store links
Clicked links. They work
> fix(app-section) Add store links

- site/web/app/themes/sage/templates/footer.php
- site/web/app/themes/sage/templates/header.php
- Links in footer
- Linked phone numbers, address and email in the footer contact widget
- Social Media links in the footer and header
- Government and DSU links in the footer
- s/Homepage/Acasă
Tested each link
> fix(links) Final links in footer/header

- site/config/misc/fiipregatitro.wordpress.2018-02-05.xml
> content(links) Added footer links

- .github/CONTRIBUTING.md
https://github.com/civictechro/guidelines
> chore(guidelines) Import CONTRIBUTING.md

- LICENSE
> chore(license) Update year

- .gitignore
> chore(.gitignore) Include OS generated files

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/contact.php
- site/web/app/themes/sage/templates/mustache/contact.mustache
> feat(contact) Add contact page

- site/composer.json
- site/composer.lock
Bump version 4.9.3 <-> 4.9.4
-
> chore(wordpress) Bump version 4.9.3 <-> 4.9.4

- site/web/app/themes/sage/gulpfile.js
`gulp watch` face reload si la modificari de `*.mustache`
Editeaza un fisier `*.mustache`, confirma ca `gulp watch` face reload
> fix(gulp) Reload browser on .mustache changes

- site/web/app/themes/sage/templates/content-single-ghid.php
- site/web/app/themes/sage/templates/mustache/guide.mustache
Ascunde card-ul de info ajutatoare daca nu exista continut pentru el
👀
> fix(guide) Don't show extra info card if it's empty

- site/web/app/lib/Entity/Guide.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/guide.mustache
Ascunde link-ul de download PDF daca acesta nu exista
- Deschis pagina ghid fara PDF, confirmat ca nu se afiseaza link catre PDF imaginar
- Deschis pagina ghid cu PDF, confirmat ca se afiseaza link catre PDF real
> fix(guide) Hide PDF link if no PDF present

- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/mustache/homepage_counter.mustache
Acum chiar numaram item-urile de pe homepage
Deschide homepage, confirma count-urile
> fix(homepage) Actually count items

- site/config/misc/acf-export-2018-02-09.json
- site/web/app/themes/sage/templates/content-plan-personal.php
Adaugat structura de date pentru plan personal in ACF
👀
> feat(plan_personal) Personal plan data structura (ACF config)

- site/web/app/lib/Entity/Guide.php
- site/web/app/themes/sage/templates/content-single-ghid.php
- site/web/app/themes/sage/templates/mustache/guide.mustache
- Numara pagini cu regex
- Daca nu gasim nr. de pagini, calculeaza dimensiunea in Kb/Mb
- Daca nu reusim nici sa gasim marimea, ascunde extra info
Testat cu mai multe PDF-uri care intra in categoriile de mai sus
> fix(guides) Proper page counter

- site/config/misc/acf-export-2018-02-10.json
- site/config/misc/plan-personal-acf-export-2018-02-10.json
- Export plan field group as a single config for import in production
- Export all fields group with the most up to date config
> fix(scaffolding) Export plan field group

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(guides) Fix list style (overflow)

- site/web/app/lib/Entity/Guide.php
- site/web/app/lib/Repository/AbstractRepository.php
- site/web/app/lib/Repository/GuideRepository.php
- site/web/app/themes/sage/templates/content-single-ghid.php
Afișează ghidurile similare setate din admin.
Am setat ghiduri similare și am testat:
- Că se afișează toate ghidurile similare acolo unde le-am setat
- Dacă nu sunt ghiduri similare, nu se afișează nimic
> fix(guides) Show related guides instead of randomly picking two

- site/web/app/themes/sage/templates/content-single-ghid.php
- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
- Centreaza recomandarile pe pagina de detaliu ghid
- Lasa ghidurile sa "curga" pe homepage
👀
> fix(guide) Center recommandations on guide detail page

- site/composer.json
- site/composer.lock
- site/web/app/lib/App.php
- site/web/app/lib/Entity/Guide.php
- site/web/app/lib/Repository/GuideRepository.php
- site/web/app/mu-plugins/fiipregatit-content.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/content-single-ghid.php
- site/web/app/themes/sage/templates/mustache/guide.mustache
Am importat `CMB2` si folosim un Meta Box pentru galerie, restrictionat la ghiduri. `ACF` nu are camp pentru galerii decat contra-cost ceea ce face dezvoltarea in regim FOSS dificila, am verificat deja cu dezvoltatorii `ACF`. 
Either way, `CMB` e o solutie nice pentru ce avem nevoie aici si functioneaza as expected.
- Urcat galerie pe un ghid, verificat ca se randeaza corect
- Verificat un ghid fara poze in galerie, verificat ca nu se randeaza deloc
> feat(gallery) Add gallery to guides via CMB

- site/web/app/themes/sage/templates/content-single-ghid.php
> fix(gallery) Don't show extra info container when no extra info available

- site/web/app/lib/Repository/GuideRepository.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/content-single-ghid.php
- Numara rezultatele reale pe homepage (imagini + videos)
Confirmat dupa uploads de imagini pe ghiduri ca se afiseaza count-ul corect pe homepage
> fix(gallery) Show overall gallery photo count on homepage

- site/config/misc/acf-export-2018-02-10-2.json
- Galeria pentru ghiduri e acum un Custom Box
- Atasamentele pentru campanii sunt tot un Custom Box
Verificat ca atat ghidurile cat si campaniile se afiseaza corect cu noua configuratie
> fix(config) New field config, without guide gallery and campaign attachments

- site/web/app/lib/Entity/Campaign.php
- site/web/app/lib/Repository/CampaignRepository.php
- site/web/app/themes/sage/templates/content-single-campanie.php
Afiseaza ghidurile sugerate (setate din admin) pe pagina de campanie. Ca si fallback, daca nu sunt ghiduri sugerate, ia primele patru ghiduri si afiseaza-le. 
👀
> fix(campaign) Use suggested guides on campaign detail page

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/contact.mustache
Pe pagina de contact afisam mereu cele doua coloane pe acelasi rand, acum sunt afisate una sub alta pe ecrane mici.
👀
> fix(contact) Display contact cols on top of each other on small screens

- site/web/app/themes/sage/templates/mustache/campaign.mustache
Afisat poza si text unul peste altul pe mobil
👀
> fix(campaign) Show image and text on top of each other on mobile

- site/web/app/themes/sage/templates/mustache/guide.mustache
By default, toate sectiunile sa fie inchise
👀
> fix(guide) By default, all accordion options are closed

- site/web/app/themes/sage/templates/listing-ghiduri.php
Adaugat inapoi header-ul cu bara de search pe listing ghiduri
👀
> fix(guide) Add search header on guide listing page

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(guide) Higher bottom padding on guides section

- site/web/app/themes/sage/assets/styles/layouts/_footer.scss
> fix(footer) Small bottom padding

- site/web/app/themes/sage/package-lock.json
- site/web/app/themes/sage/package.json
> chore(travis) Try to fix the build (gulp production failing)

- site/web/app/themes/sage/assets/styles/layouts/_footer.scss
> fix(footer) Higher padding on top

- site/web/app/lib/App.php
- site/web/app/themes/sage/home.php
> fix(campaigns) Show see all button on campaign section

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(counter) Larger font size on count, homepage

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/assets/styles/components/_forms.scss
> fix(search) Smaller border on search box

- site/web/app/themes/sage/assets/styles/components/_forms.scss
> fix(search) Make search box larger, match design

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
> fix(nav) Larger margin between items

- site/web/app/themes/sage/assets/styles/components/_forms.scss
> fix(search) Center icon on search button

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(guide) Arrows down when closed, arrows up when open

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(plan) Arrows down when closed, up when open

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(campaign) Arrows down when closed, up when open

- site/web/app/themes/sage/templates/mustache/guide.mustache
> fix(guide) Allow all sections to be opened at the same time

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/plan_personal.mustache
> fix(personal_plan) Don't show images on mobile

- site/config/misc/acf-export-2018-02-13.json
- site/web/app/lib/CustomPage/PersonalPlanPage.php
- site/web/app/lib/Entity/PersonalPlan.php
- site/web/app/themes/sage/templates/content-plan-personal.php
> fix(personal_plan) Add one more section to the list

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
Schimbate media query-urile astfel incat sa fie la baza fisierului. 
Adaptat meniul de mobile astfel incat sa nu mai aiba intreruperi.
> fix(mobile) No glitch when opening the menu

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- Fixed menus for tablets and phones. 
- Comentat menu-item pentru ca facea un spatiu prea mare intre elemente, am adaugat padding (pentru ca userul sa poata da tap pe toata inaltimea elementului).
> fix(mobile) Fixed glitch also for larger devices

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/mustache/app_promo.mustache
- Vertical center align personal plan
- Vertical center align app promo
N/A
> fix(homepage) Vertically center align photos -> text

- site/web/app/themes/sage/404.php
> fix(404) Translate error message

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
Rezolvat problema meniului expandat in momentul redimensionarii ferestrei.
> Fixed Menu glitch expanding #198

- site/web/app/themes/sage/templates/mustache/contact.mustache
> fix(contact) Responsive columns for tiny screens too

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(contact) Better contact forms style (match theme)

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Adaugat o serie de elemente responsive. work in progress.
partial #123
> Step1 - responsive font size for different elements. 

- site/web/app/themes/sage/templates/header.php
> fix(header) Update tagline

- site/composer.json
- site/composer.lock
> fix(plugin) New Pirate Forms plugin patch

- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Adaugat linkuri pe butoanele din homepage
> fix(homepage) Add links to buttons on homepage

- site/web/app/lib/App.php
- site/web/app/lib/Entity/Campaign.php
- site/web/app/lib/Repository/CampaignRepository.php
- site/web/app/mu-plugins/fiipregatit-content.php
- site/web/app/themes/sage/templates/content-single-campanie.php
- site/web/app/themes/sage/templates/mustache/campaign.mustache
- Add repeater field for {title, url} pair in backoffice
- Display videos in a lightbox on the frontend
http://nimb.ws/OtgEmT
> feat(campaign) Allow attaching videos to campaigns

- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
> fix(guides) s/ghiduri educative/ghiduri

- site/config/misc/prim-ajutor-2-acf-export-2018-02-22.json
- site/config/misc/prim-ajutor-acf-export-2018-02-22.json
- site/web/app/lib/App.php
- site/web/app/lib/CustomPage/BaseCustomPage.php
- site/web/app/lib/CustomPage/FirstAidPage.php
- site/web/app/lib/CustomPageManager.php
- site/web/app/lib/Entity/FirstAid.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/content-prim-ajutor.php
- site/web/app/themes/sage/templates/mustache/first_aid.mustache
- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
- First aid page and custom fields
- Show first aid page box together with guides on homepage
- First aid detail page accordion
> feat(first_aid) Add First Aid page

- site/web/app/lib/App.php
> fix(homepage) 8 guides on homepage, including first aid

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- site/web/app/themes/sage/templates/header.php
> fix(header) Update copy and make more responsive

- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
> fix(home) Show 4 campaigns only on md screens

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/assets/styles/layouts/_footer.scss
- site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
Adaugat link-uri pe:
- titlu campanie
- poza campanie
👀
> fix(campaign) Link title, photo

- site/web/app/themes/sage/templates/listing-campanii.php
Adaugat search jumbotron pe pagina de listing campanii
N/A
> fix(campaigns) Add search header on campaign listing page

- site/web/app/themes/sage/templates/content-plan-personal.php
Afisam toate campaniile pe pagina de plan personal, afiseaza doar 3 (sau 4 daca e ecran mediu)
👀
> fix(campaigns) Show only 3 campaigns on personal plan page

- site/web/app/themes/sage/templates/content-plan-personal.php
Colapseaza toate item-urile din plan personal by default
👀
> fix(personal_plan) Collapse all items by default

- site/web/app/themes/sage/templates/listing-ghiduri.php
Adaugat Prim Ajutor in listing-ul de ghiduri
> fix(guides) Include First Aid in the listing

- site/web/app/themes/sage/templates/content-single-ghid.php
Adaugat link catre prim ajutor in sidebar pe pagina de detaliu ghid
👀
> fix(guide) Add First Aid link in sidebar

- site/web/app/themes/sage/templates/content-single-ghid.php
Daca esti pe pagina de ghid "X", atunci nu mai ai link catre ghidul "X" in sidebar. 
👀
> fix(guide) Don't show link to same guide in sidebar

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/footer.php
- site/web/app/themes/sage/templates/mustache/campaign.mustache
Afișează titlu + close button pe lightbox în pagina de campanie
> fix(campaign) Always show close button on lightbox

- site/web/app/themes/sage/404.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/404.mustache
> fix(404) "Four, oh four" custom template

- site/web/app/themes/sage/templates/listing-campanii.php
- site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
Scos data publicare din campanii
> fix(campaign) Don't show publishing date

- site/web/app/themes/sage/algolia/instantsearch.php
Schimbat template pentru negasit rezultate conform cu design.
https://www.useloom.com/share/46500af181d344099d63529e7a81bcaa
> fix(search) No search results template

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- Always two rows at most
- Handle very tiny screens
https://www.useloom.com/share/0ceae32c223949919d14bfbb472ad2ed
> fix(tagline) Make tagline more responsive

- site/web/app/themes/sage/assets/styles/components/_forms.scss
Placeholder: gri, italic
Input text: negru, normal
https://www.useloom.com/share/28d6de52aa8f4143bd5fc97ca6a003e9
> fix(search) Make placeholder text italic and grey only

- site/web/app/themes/sage/assets/styles/common/_global.scss
Facut mai mari butoanele din acordeon pentru plan personal
> fix(personal_plan) Larger accordeon buttons

- site/web/app/themes/sage/assets/styles/common/_global.scss
- Wrap pentru titluri lungi
- Pozitionare mereu pe centru (vertical) pentru chevron
https://www.useloom.com/share/812dfeea28ac4d67a544dd3a7fd701ee
>  fix(first_aid) Wrap long accordion titles, have chevron vert. positioned

- site/web/app/themes/sage/templates/mustache/first_aid.mustache
Videos din prim ajutor sunt acum responsive
Testat cu diverse marimi de browser/mobil
> fix(first_aid) Responsive videos

- site/web/app/themes/sage/templates/mustache/campaign.mustache
> fix(campaign) Updated copy on campaign "see attachments" button

- site/web/app/themes/sage/templates/footer.php
Adaugat Google Analytics pentru staging (fiipregatit.claudiuceia.ro)
N/A
> chore(analytics) Add Google Analytics tracking code

- site/web/app/themes/sage/lib/Algolia/GuideIndexCustomFields.php
> hotfix(search) Smaller request to Algolia

- site/composer.json
- site/composer.lock
> fix(plugins) Add importer

- site/web/app/themes/sage/templates/footer.php
> fix(analytics) Add prod analytics (fiipregatit.ro)

- README.md
- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/markdown/Editează plan personal.md
- site/web/app/themes/sage/templates/mustache/plan_personal.mustache
Schimbat "Plan personal" in "Trusa Supravietuire"
👀
> fix(personal_plan) s/plan personal/trusa supravietuire

- site/web/app/themes/sage/assets/styles/layouts/_footer.scss
- Afiseaza link de "Contribuie" sub logo si pe mobil
- Spatiere footer pe mobil, whitespace 
👁
> fix(footer) Spacing on mobile, show contribute under logo

- site/web/app/themes/sage/assets/styles/common/_global.scss
Actualizat stare hover  conform design
> fix(guides) Hover state update

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Permite click pe toata cartograma
N/A
> fix(guides) Allow clicking the whole box

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/content-prim-ajutor.php
- site/web/app/themes/sage/templates/content-single-campanie.php
- site/web/app/themes/sage/templates/content-single-ghid.php
- site/web/app/themes/sage/templates/listing-ghiduri.php
- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Vezi #284 
https://www.useloom.com/share/0d534f23257b4a32bcf731f041f171e9
> fix(guides) Guide box rendering overhaul

- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Hotfix: nu sttretch-ui butoanele de pe ghiduri pe ecrane mici
👀
> fix(guide) Don't widen button on small screens

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- letter spacing meniu
- contrast mai mare meniu
- spatiere mai mare intre link-uri
👀
> fix(menu) Higher menu contrast

- site/web/app/themes/sage/assets/styles/common/_global.scss
- mai aproape de content
- mai mare
👀
> fix(see_all) See all button - better visibility

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- nu schimba letter spacing / culoare meniu pe mobil
N/A
> fix(header) Don't change color/spacing on mobile

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
- border 1px #933 pe butoanele de campanii
👀
> fix(campaign) Better visibility on campaign button

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/home.php
> fix(survival_kit) Add link on the illustration as well

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- site/web/app/themes/sage/functions.php
- adaugat link spre homepage in meniu (icon)
👀
> fix(header) Add homepage link

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- animate header underline
https://www.useloom.com/share/4a851478cd9f48a798334ba5b4cdbd05
> fix(header) Animate underline

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- distanta mai mica intre item-uri, sa incapa si pe tableta
👀
> fix(header) Don't break menu on medium screens

- site/web/app/themes/sage/assets/styles/layouts/_footer.scss
- site/web/app/themes/sage/templates/footer.php
- marit spatiu intre items in footer pe mobil
- centrat link-uri in footer pe mobil
> fix(footer) Better mobile layout

- site/web/app/themes/sage/assets/styles/common/_global.scss
- schimbat border, text si chevron in rosu, din gri, pe dropdown-ul din detaliu ghid pe mobil
> fix(guides) Make dropdown more visible on mobile

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/listing-ghiduri.php
- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
- facut prim ajutor sa arate ca celelalte ghiduri
👀
> fix(guides) First aid box starts looks like a regular box

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/assets/styles/components/_buttons.scss
- site/web/app/themes/sage/templates/content-galerie-video.php
- site/web/app/themes/sage/templates/mustache/homepage_counter.mustache
- site/web/app/themes/sage/templates/mustache/video_gallery.mustache
- Adaugat galerie video (linked din counter homepage)
**Atentie, e slow pentru ca e in mediu de dev**: https://www.useloom.com/share/ad387796594748c284ec404c20ca5264
> feat(video_gallery) Add video gallery (linked from homepage)

- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/mustache/homepage_counter.mustache
- +1 pentru ghiduri (include prim ajutor)
- link din counter in pagina de ghiduri
👀
> fix(homepage) Link guides from count section

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/content-galerie-foto.php
- site/web/app/themes/sage/templates/mustache/homepage_counter.mustache
- site/web/app/themes/sage/templates/mustache/photo_gallery.mustache
- adaugat pagina galerie foto (pentru foto din toate ghidurile)
- link pagina din counter homepage
👀
> feat(photo_gallery) Link from homepage counter to photo gallery

- site/web/app/themes/sage/assets/styles/common/_global.scss
- redimensioneaza pictogramele de la ghiduri (if needed)
- uploadat svg mai mare decat dimensiunea asteptata 
- verificat ca se scaleaza astfel incat sa incapa in zona predefinita
> fix(guide) Limit maximum guide icon size

- site/web/app/lib/CustomPage/FirstAidPage.php
- site/web/app/lib/Entity/FirstAid.php
- site/web/app/themes/sage/templates/content-prim-ajutor.php
- ordine sectiuni corecta
- adaugat apel 112
👁
> fix(first_guide) Add 112, fix order

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
- nu arata underline pe mobil
👀
> fix(header) Don't show underline on mobile

- site/web/app/themes/sage/templates/contact.php
- site/web/app/themes/sage/templates/mustache/contact.mustache
- clean up recaptcha code
- don't include recaptcha script
👀
> fix(contact) Clean up recaptcha remains

- site/web/app/themes/sage/assets/styles/common/_global.scss
- font mai mare
- header mai mare
- logo grayscale + opacitate 50%
- hover mai contrastant
👀
> fix(search) Search dropdown UI enhancements

- site/composer.json
- site/composer.lock
- site/web/app/lib/CustomPage/BaseCustomPage.php
- site/web/app/lib/CustomPage/PersonalPlanPage.php
- site/web/app/lib/CustomPageManager.php
- site/web/app/themes/sage/algolia/autocomplete.php
- site/web/app/themes/sage/algolia/instantsearch.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/functions.php
- site/web/app/themes/sage/lib/Algolia/AboutIndexCustomFields.php
- site/web/app/themes/sage/lib/Algolia/CampaignIndexCustomFields.php
- site/web/app/themes/sage/lib/Algolia/FirstAidIndexCustomFields.php
- site/web/app/themes/sage/lib/Algolia/GuideIndexCustomFields.php
- site/web/app/themes/sage/lib/Algolia/IndexCustomFields.php
- site/web/app/themes/sage/lib/Algolia/NoOpIndexCustomFields.php
- site/web/app/themes/sage/lib/Algolia/PersonalPlanIndexCustomFields.php
- site/web/app/themes/sage/search.php
- Dropdown design
- Search results design
- Custom index
- Index settings
- Patched algolia wordpress plugin
https://www.useloom.com/share/6732ea4340554250936e0722bfc3b06d
Search Results for “cutremur” – dev.fiipregatit.ro
> feat(search) Proper search implementation (v1)

- site/web/app/themes/sage/functions.php
> fix(search) attributesToIndex is deprecated

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/despre.mustache
- site/web/app/themes/sage/templates/mustache/guide.mustache
> fix(about) Fix dropdown menu on small screens

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(guide) Stop rendering dropdown opts mid-screen (as much as possible)

- site/web/app/themes/sage/templates/mustache/guide_listing.mustache
> fix(first_aid) Allow setting color for first aid icon as well

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
> fix(header) Higher spacing on mobile (navigation)

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(campaigns) Mobile spacing between campaigns

- site/web/app/themes/sage/assets/styles/layouts/_footer.scss
- site/web/app/themes/sage/templates/footer.php
> fix(footer) Mobile link spacing in footer

- site/web/app/themes/sage/templates/mustache/homepage_counter.mustache
> fix(home) Change camera icon with image icon in counter bar

- site/web/app/themes/sage/algolia/autocomplete.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/jumbotron.mustache
- Scroll to top on focus
- Replace blue accent color with #933
- Fit as much as the image as possible in the thumbnail
- Better thumbnail <=> text alignment
- Grayscale Algolia logo
- Border and white bg instead of gray bg
👀
> fix(search) Dropdown enhancements before launch

- site/web/app/themes/sage/algolia/instantsearch.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/assets/styles/components/_forms.scss
- make search box look like box on other pages
- move svg icon in input on the right side, not on the left
- column less wide on search results page
- hover state for search result headers
👀
> fix(search) Search results page enhancement

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/guide.mustache
> fix(guide) Add lightbox to gallery to handle weird image aspect ratios

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/templates/mustache/photo_gallery.mustache
> fix(gallery) Add lightbox to gallery for weird-aspect-ratio photos

- site/web/app/themes/sage/algolia/instantsearch.php
- search pagination not working properly, keep 10 results for now
N/A
> fix(search) Remove pagination

- site/composer.json
- site/composer.lock
- PR-ul a ajuns in prod, `2.10.0`, nu mai folosi fork-ul civictech
👀
> fix(plugins) Use Algolia official plugin again, PR landed

- site/web/app/themes/sage/templates/mustache/plan_personal.mustache
> fix(trusa) Fix header capitalization

- site/web/app/themes/sage/algolia/autocomplete.php
> fix(search) Fix forever escape bug

- site/web/app/themes/sage/functions.php
> fix(search) Fix auto-index

- site/web/app/themes/sage/templates/mustache/plan_personal.mustache
> fix(trusa) s/trusa/plan familie

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(guide) No spacing on top of sidebar

- site/web/app/themes/sage/templates/content-single-campanie.php
> fix(campaign) Use a less resource intensive way to render attachments

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(guide) Larger spacing between bottom and button

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(search) Make autocomplete more mobile-friendly

- site/web/app/themes/sage/algolia/instantsearch.php
- site/web/app/themes/sage/templates/mustache/404.mustache
> fix(search) Wider 'not found' section on search page

- site/web/app/themes/sage/templates/mustache/partials/algolia_search_page_form.mustache
> fix(search) Algolia grayscale, search page

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(search) Larger bottom spacing on search page

- site/web/app/themes/sage/templates/footer.php
> fix(footer) Larger partner links in footer

- site/web/app/themes/sage/templates/mustache/plan_personal.mustache
> fix(trusa) No titles on personal plan page

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(campaign) Larger vertical spacing between campaigns on desktop

- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/home.php
- site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
> fix(home) larger see all buttons

- site/web/app/themes/sage/assets/styles/layouts/_header.scss
> fix(header) No underline on social media icons

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(guides) Always Roboto content

- site/web/app/themes/sage/algolia/autocomplete.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(search) thumbs for guides should contain full icon

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(search) fit guide ico in thumb

- site/web/app/themes/sage/home.php
> fix(home) update CTA copy to reflect page name change

- site/web/app/lib/App.php
- site/web/app/lib/CustomPage/AboutPage.php
- site/web/app/lib/Entity/About.php
- site/web/app/mu-plugins/fiipregatit-content.php
- site/web/app/themes/sage/assets/styles/common/_global.scss
- site/web/app/themes/sage/functions.php
- site/web/app/themes/sage/templates/despre.php
- site/web/app/themes/sage/templates/mustache/despre.mustache
> feat(about) Add partners page layout

- site/web/app/themes/sage/lib/Algolia/AboutIndexCustomFields.php
> fix(search) reindex partners content

- site/web/app/themes/sage/templates/head.php
> fix(cookie) Cookie consent popup

- site/web/app/themes/sage/lib/Meta/GenericMetaGenerator.php
- site/web/app/themes/sage/lib/Meta/MetaGenerator.php
- site/web/app/themes/sage/templates/head.php
> fix(meta) Include homepage meta

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(home) Counters hover state

- site/web/app/themes/sage/templates/footer.php
> fix(footer) Fix permalink

- site/web/app/themes/sage/templates/footer.php
- site/web/app/themes/sage/templates/header.php
> fix(social) open in new tab

- site/web/app/themes/sage/templates/mustache/despre.mustache
> fix(about) don't escape partners wysiwyg

- site/web/app/themes/sage/templates/footer.php
- site/web/app/themes/sage/templates/mustache/contact.mustache
> fix(maps) open in new tab

- site/web/app/themes/sage/templates/mustache/app_promo.mustache
> fix(home) open apps in new tab

- site/web/app/themes/sage/assets/styles/common/_global.scss
> fix(campaign) larger spacing between attachments

- site/web/app/lib/CustomPageManager.php
- site/web/app/lib/Entity/Link.php
- site/web/app/lib/RepoManager.php
- site/web/app/lib/Repository/AbstractRepository.php
- site/web/app/lib/Repository/CampaignRepository.php
- site/web/app/lib/Repository/LinkRepository.php
- site/web/app/themes/sage/templates/footer.php
> fix(footer) proper links in footer

- site/web/app/themes/sage/templates/content-galerie-foto.php
- site/web/app/themes/sage/templates/content-single-ghid.php
- site/web/app/themes/sage/templates/mustache/guide.mustache
- site/web/app/themes/sage/templates/mustache/photo_gallery.mustache
> fix(galleries) don't show arrows if single photo

- site/web/app/themes/sage/algolia/instantsearch.php
> fix(search) show label under title for search results

- site/web/app/themes/sage/templates/footer.php
> feat(pingdom) Visitor Insights - RUM

- README.md
> chore(readme) update visual

- site/composer.json
- site/composer.lock
> feat(plugins) add cerber

- site/web/app/themes/sage/templates/mustache/404.mustache
> fix(404) update message

- README.md
> chore(readme) launch updates

- README.md
- add uptime, "help wanted" issues badges
- remove status, issues badges
> chore(readme) restructure badges

- site/web/app/themes/sage/algolia/autocomplete.php
- site/web/app/themes/sage/algolia/instantsearch.php
> hotfix(xss) patch security issue

- site/web/app/themes/sage/algolia/autocomplete.php
- site/web/app/themes/sage/algolia/instantsearch.php
Reverts civictechro/fiipregatit.ro#453
> Revert "hotfix(xss) patch security issue"

- site/web/app/themes/sage/algolia/instantsearch.php
> hotfix(search) escape query

- site/web/app/lib/App.php
> fix(footer) Allow more links in the footer
